# Generated by Django 4.0.3 on 2022-06-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
