# Generated by Django 4.0.3 on 2022-06-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_faculty_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
