# Generated by Django 4.0.3 on 2022-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subject_fname_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='dept',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='subjects',
        ),
        migrations.AddField(
            model_name='faculty',
            name='subjects',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
